test_lab_bundle_prisma:
    resource: "@TestLabBundlePrismaBundle/Resources/config/routing.yml"
    prefix:   /

tes:
    resource: "@TesBundle/Controller/"
    type:     annotation
    prefix:   /


core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
