<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AcquittanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcquittanceRepository extends EntityRepository
{
    public function getAcquittance() {
        $qb = $this->createQueryBuilder('a');

        return $qb->getQuery();
    }
}
